services:
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: "opensearchproject/opensearch:latest"
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # This is the name of the cluster
      - node.name=opensearch-node1 # This is the name of the node
      - discovery.seed_hosts=opensearch-node1 # This is the list of nodes in the cluster
      - cluster.initial_master_nodes=opensearch-node1 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Lock the memory on startup
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # This is the data volume
      - opensearch-logs1:/usr/share/opensearch/logs # This is the logs volume
      - opensearch-config1:/usr/share/opensearch/config # This is the config volume
    ports:
      - "9200:9200" # This is the port OpenSearch listens on
      - "9600:9600" # This is the port for the performance analyzer
    networks:
      - net-connectors # This is the name of the Docker network
  opensearch-dashboards:
    image: "opensearchproject/opensearch-dashboards:latest"
    container_name: opensearch-dashboards
    ports:
      - "5601:5601" # This is the port OpenSearch Dashboards listens on
    expose:
      - "5601" # This is the port OpenSearch Dashboards listens on
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch-node1:9200"] # This is the list of OpenSearch nodes
    networks:
      - net-connectors
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./connectors/minio/data:/data
    env_file:
      - ./connectors/minio/minio.env
    command: server --console-address ":9001" /data
    networks:
      - net-connectors
  custom_script:
    build:
      context: .
      dockerfile: ./connectors/minio/Dockerfile
    container_name: custom_script
    volumes:
      - ./connectors/minio/load_data.sh:/load_data.sh
      - ../data:/data
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: /load_data.sh
    env_file:
      - ./connectors/minio/minio.env
    networks:
      - net-connectors

volumes:
    opensearch-data1:
    opensearch-logs1:
    opensearch-config1:

networks:
    net-connectors:
