services:
  glue_spark_submit:
    image: "amazon/aws-glue-libs:glue_libs_4.0.0_image_01"
    container_name: glue_spark_submit
    volumes:
      - ~/.aws:/home/glue_user/.aws
      - $WORKSPACE_LOCATION:/home/glue_user/workspace/
    environment:
      - AWS_PROFILE=$PROFILE_NAME
      - DISABLE_SSL=true
    ports:
      - "4040:4040"
      - "18080:18080"
    command: spark-submit /home/glue_user/workspace/src/$SCRIPT_FILE_NAME
    tty: true
    stdin_open: true
    restart: "no"
    networks:
      - net-connectors
    depends_on:
      - opensearch-node1
      - opensearch-dashboards
