services:
  glue_jupyter_lab:
    image: "amazon/aws-glue-libs:glue_libs_4.0.0_image_01"
    container_name: glue_jupyter_lab
    ports:
      - "8888:8888"
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
    volumes:
      - ~/.aws:/home/glue_user/.aws
      - $JUPYTER_WORKSPACE_LOCATION:/home/glue_user/workspace/jupyter_workspace
    environment:
      - AWS_PROFILE=$PROFILE_NAME
      - DISABLE_SSL=true
      - MINIO_BUCKET=dummy-bucket
      - MINIO_PREFIX=dummy-data
    env_file:
      - ./connectors/minio/minio.env
    command: /home/glue_user/jupyter/jupyter_start.sh
    tty: true
    stdin_open: true
    restart: "no"
    networks:
      - net-connectors
    depends_on:
      - opensearch-node1
      - opensearch-dashboards
